### PR TITLE
Update lib.rs

### PR DESCRIPTION
**Pull request by Kofituo**
add wasm support and make functions const

### CODE REVIEW

**Comment by phimuemue** [comment]
Hi there, thanks for the input.

As it stands, this PR throws different things together, namely (at least):
* New largest number type `u128`/`i128`: Fine with me.
* `std` -> `core`: Fine with me.
* `const_trait_impl`: I think this requires unstable Rust, and I prefer to target stable rust, so I won't include this.
* Formatting changes: Fine with me.

I'd be happy to merge the relevant parts (not the unstable one). Could you please split them into three separate commits?

**Comment by Kofituo** [comment]
Sure

**Comment by phimuemue** [comment]
I hope I‘m not missing something, but I cannot recognize a clear direction in the commits - it seems that the second and third commit undo some changes from the first.

Could you just start from scratch and have separate commits for:

* u128/i128
* std->core
* Formatting changes

I think you can force-push to this brach, and the PR will be updated accordingly.

**Comment by phimuemue** [comment]
Hi @Kofituo, thanks for bringing this to my attention.

I went back to my source and found that I already had the [128-bit](https://github.com/phimuemue/rs_as_num/commit/a63375cfcc2121166531add456f4d14531847b69) types pending. I also updated [`std`->`core`](https://github.com/phimuemue/rs_as_num/commit/edc3211bb3f44afd4d6dffa865856c9297a087e4).

I'll close this PR, and would like to ask you to open another one if there's anything else you need.

**Pull request closed without merging**
